In [2]:
import pandas as pd
import numpy as np

### Summarizing and Computing Descriptive Statistics

In [4]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                    [np.nan, np.nan], [0.75, -1.3]],
                    index=["a", "b", "c", "d"],
                    columns=["one", "two"])
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [ ]:
# return sum of each column's values
df.sum()

one    9.25
two   -5.80
dtype: float64

In [ ]:
# returns sums across the columns
df.sum(axis="columns")

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [ ]:
# any NA value in a row or column names the corresponding result NA
df.sum(axis="index", skipna=False)

one   NaN
two   NaN
dtype: float64

In [8]:
df.sum(axis="columns", skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [9]:
# produce multiple summary statistics in one shot
df.describe()

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [ ]:
# nonnumeric data - describe method returns alternative summary statistics
obj = pd.Series(["a", "a", "b", "c"] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Unique Values, Value Counts, and Membership

In [12]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: str

In [ ]:
# gives you an array of the unique values in a Series
uniques = obj.unique()
uniques

<ArrowStringArray>
['c', 'a', 'd', 'b']
Length: 4, dtype: str

In [ ]:
# value_counts computes a Series containing value frequencies
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [ ]:
# a vectorized set membership check
mask = obj.isin(["b", "c"])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [ ]:
# can be usefuk in filtering a dataset down to a subset of values
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: str